### PR TITLE
Added Footer & Login Component

### PR DESCRIPTION
**Pull request by tharunbirla**
Added Footer & Login Component.
- [Proposal] React Footer Component #11
- [Proposal] A Frontend React Sign-in Component #12

### CODE REVIEW

**Comment by tharunbirla** [comment]
@atharva0300 Please verify ✌️

**Review by unnikrishnan2002 — COMMENTED** [review]
## Suggestions from my side 
- Resolve the merge conflicts
- Don't commit the `package.json` and `package-lock.json` files
- Add a line at the end of `Login.css` , `Footer.js` , and `Login.js`
- Add screenshots/gifs supporting your changes

Fix these , if @777ahesh Or @atharva0300 approves the suggestions 
Rest will be reviewed by the them🙂

**Comment by tharunbirla** [comment]
@unnikrishnan2002 & @atharva0300  
- I have added [Simple react footer](https://www.npmjs.com/package/simple-react-footer) package for footer.
- Footer component
footer
- Login component
login

**Comment by unnikrishnan2002** [comment]
@tharunbirla remove the commits of `package.json` and `package-lock.json` files

**Comment by tharunbirla** [comment]
@unnikrishnan2002 I have added  `simple react footer` package as dependency so the `package.json` and `package-lock.json` files are changed.

PS: there were extra spaces in line 2&17 in `package.json`

**Comment by unnikrishnan2002** [comment]
Okay 👍. @atharva0300 @777ahesh Please review the changes🙂

**Review by atharva0300 — APPROVED** [review]

**Pull request merged**
