### PR TITLE
react-router feature added

### PR DESCRIPTION
**Pull request by pratistha-05**
navigation purposes

# Related Issue
Fixes #issue_number

# Changes Proposed
-- Breifly describe the changes you made --

# Additional Information
-- If you have any additional information to add , do it here --

# Files Changed
- file 1
- file 2
- file 3

# Checklist
Check all the boxes [X] that applies
- [ ] I have asked/communicated about the issue before opening a PR
- [x] I have checked that there are no existing PR open for the same issue
- [x] I have tested the code locally before submission
- [x] My submission doesn't break any existing component or feature
- [ ] I have updated the documentation accordingly *{if needed}*
- [x] I have added my name and username to [Contributors.md](https://github.com/atharva0300/Meme-Generator/blob/main/Contributors.md) *{ provided my name and username was not added before}*

# Screenshots
-- Add the screenshots/gifs supporting your changes --

# Note to the Maintainers/Reviewers
-- If you have something for the maintainers/reviewers you can add that here --

### CODE REVIEW

**Review by unnikrishnan2002 — CHANGES_REQUESTED** [review]
@pratistha-05 . You don't have to commit the `ISSUE_TEMPLATE.md` and `PULL_REQUEST.md` . You just had to mention the changes and all while making the pull request . Anyway since you are not raising and issue don't need to do anything with the Issue template . Please remove these changes and commit again.

**Comment by pratistha-05** [comment]
I've removed undesirable changes. Previously I had added react-router and some files with blank react template .

**Comment by unnikrishnan2002** [comment]
> I've removed undesirable changes. Previously I had added react-router and some files with blank react template .

The maintainers are a little busy . They will get back to you soon 😄 .

**Review by 777ahesh — APPROVED** [review]
Yep, It is working properly in my  Local System.
I don't find any bugs in it @atharva0300  you can merge this pull request

**Pull request merged**
