### PR TITLE
Navbar created 

### LINKED ISSUE #8: Create a Responsive Navbar Component for the Meme-Generator
The Navbar should contain Home About Contact us and Workspace Links.
Try to make the Navbar Responsive.

### PR DESCRIPTION
**Pull request by unnikrishnan2002**
# Description
Responsive Navbar component is added.

# Additional Information
I have used bootstrap to add the Navbar component which has the title of the app at the top left following with the `Home`, `About`, `Contact Us` and `Workspace` links. When the screen size reduces, a collapsible button appears which contains the links of the above mentioned Navbar components

# Screenshots
navbar1
ezgif com-gif-maker

# Files changed
- **public/index.html - Modifed**
- **src/App.js - Modified**
- **src/ - Created**

# Related Issue
fixes #8

### CODE REVIEW

**Review by 777ahesh — COMMENTED** [review]
Can you add a logo to the Navbar

**Comment by 777ahesh** [comment]
You have used default Navbar from bootstrap Website Not a problem. 
But try to edit the font if You can and add the logo

**Comment by unnikrishnan2002** [comment]
Okay will try to do that👍

**Comment by unnikrishnan2002** [comment]
> You have used default Navbar from bootstrap Website Not a problem. But try to edit the font if You can and add the logo

Done

**Comment by 777ahesh** [comment]
Yep just checking the code...

**Pull request merged**
